---
nginx_revproxy_sites:                                         # List of sites to reverse proxy
  ev-gen.info:                                                # Domain name
    client_max_body_size: "256M"
    proxy_read_timeout: "360"
    domains:                                                  # List of server_name aliases
      - ev-gen.info
    upstreams:                                                # List of Upstreams
      - {backend_address: 192.168.10.100, backend_port: 80}
    ssl: true                                                 # Set to True if you want to redirect http to https
    hsts_max_age: 63072000                                    # Set HSTS header with max-age defined
    letsencrypt: true                                        # Set to True if you want use letsencrypt
    letsencrypt_email: "emivanchenko389@gmail.com"

  gitlab.ev-gen.info:                                                # Domain name
    client_max_body_size: "256M"
    proxy_read_timeout: "360"
    domains:                                                  # List of server_name aliases
      - gitlab.ev-gen.info
    upstreams:                                                # List of Upstreams
      - {backend_address: 192.168.10.21, backend_port: 80}
    ssl: true                                                 # Set to True if you want to redirect http to https
    hsts_max_age: 63072000                                    # Set HSTS header with max-age defined
    letsencrypt: true                                        # Set to True if you want use letsencrypt
    letsencrypt_email: "emivanchenko389@gmail.com"

  app.ev-gen.info:                                                # Domain name
    client_max_body_size: "256M"
    proxy_read_timeout: "360"
    domains:                                                  # List of server_name aliases
      - app.ev-gen.info
    upstreams:                                                # List of Upstreams
      - {backend_address: 192.168.10.35, backend_port: 80}
    ssl: true                                                 # Set to True if you want to redirect http to https
    hsts_max_age: 63072000                                    # Set HSTS header with max-age defined
    letsencrypt: true                                        # Set to True if you want use letsencrypt
    letsencrypt_email: "emivanchenko389@gmail.com"

  grafana.ev-gen.info:                                                # Domain name
    client_max_body_size: "256M"
    proxy_read_timeout: "360"
    domains:                                                  # List of server_name aliases
      - grafana.ev-gen.info
    upstreams:                                                # List of Upstreams
      - {backend_address: 192.168.10.24, backend_port: 3000}
    ssl: true                                                 # Set to True if you want to redirect http to https
    hsts_max_age: 63072000                                    # Set HSTS header with max-age defined
    letsencrypt: true                                        # Set to True if you want use letsencrypt
    letsencrypt_email: "emivanchenko389@gmail.com"

  alertmanager.ev-gen.info:                                                # Domain name
    client_max_body_size: "256M"
    proxy_read_timeout: "360"
    domains:                                                  # List of server_name aliases
      - alertmanager.ev-gen.info
    upstreams:                                                # List of Upstreams
      - {backend_address: 192.168.10.24, backend_port: 9093}
    ssl: true                                                 # Set to True if you want to redirect http to https
    hsts_max_age: 63072000                                    # Set HSTS header with max-age defined
    letsencrypt: true                                        # Set to True if you want use letsencrypt
    letsencrypt_email: "emivanchenko389@gmail.com"

  prometheus.ev-gen.info:                                                # Domain name
    client_max_body_size: "256M"
    proxy_read_timeout: "360"
    domains:                                                  # List of server_name aliases
      - prometheus.ev-gen.info
    upstreams:                                                # List of Upstreams
      - {backend_address: 192.168.10.24, backend_port: 9090}
    ssl: true                                                 # Set to True if you want to redirect http to https
    hsts_max_age: 63072000                                    # Set HSTS header with max-age defined
    letsencrypt: true                                        # Set to True if you want use letsencrypt
    letsencrypt_email: "emivanchenko389@gmail.com"
