---
- name: Configure replication on the slave.
  mysql_replication:
    mode: changeprimary
    master_host: 192.168.10.24
    master_user: wordpress
    master_password: wordpress
  ignore_errors: true

- name: Start replication.
  mysql_replication: mode=startreplica
